"""add fields description and doi to Sources

Revision ID: 0b6d7ef458ee
Revises: 216ded47ba65
Create Date: 2025-09-25 12:28:48.938802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6d7ef458ee'
down_revision: Union[str, Sequence[str], None] = '216ded47ba65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('doi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'doi')
    op.drop_column('sources', 'description')
    # ### end Alembic commands ###
