"""Remove UniqueConstraint

Revision ID: 216ded47ba65
Revises: 530103396fa8
Create Date: 2025-09-25 11:10:01.472469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216ded47ba65'
down_revision: Union[str, Sequence[str], None] = '530103396fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_landslide_record'), 'landslides', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_landslide_record'), 'landslides', ['type', 'date', 'description', 'geom'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
