"""split description field

Revision ID: 49c41432f3af
Revises: fe8c60478967
Create Date: 2025-09-30 14:05:37.169138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c41432f3af'
down_revision: Union[str, Sequence[str], None] = 'fe8c60478967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslides', sa.Column('report', sa.String(), nullable=True))
    op.add_column('landslides', sa.Column('report_source', sa.String(), nullable=True))
    op.add_column('landslides', sa.Column('report_url', sa.String(), nullable=True))
    op.drop_column('landslides', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslides', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('landslides', 'report_url')
    op.drop_column('landslides', 'report_source')
    op.drop_column('landslides', 'report')
    # ### end Alembic commands ###
