"""UniqueConstraint for landslides

Revision ID: 530103396fa8
Revises: d786f1744f46
Create Date: 2025-09-23 08:10:41.231653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530103396fa8'
down_revision: Union[str, Sequence[str], None] = 'd786f1744f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_landslide_record', 'landslides', ['type', 'date', 'description', 'geom'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_landslide_record', 'landslides', type_='unique')
    # ### end Alembic commands ###
