"""Classification table to replace variable types

Revision ID: 69068a354c0e
Revises: 49c41432f3af
Create Date: 2025-10-03 08:31:51.264368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69068a354c0e'
down_revision: Union[str, Sequence[str], None] = '49c41432f3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('landslides', sa.Column('classification_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'landslides', 'classification', ['classification_id'], ['id'])
    op.drop_column('landslides', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslides', sa.Column('type', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'landslides', type_='foreignkey')
    op.drop_column('landslides', 'classification_id')
    op.drop_table('classification')
    # ### end Alembic commands ###
