"""Remove unused Polygon column

Revision ID: e2839191dbbe
Revises: 69068a354c0e
Create Date: 2025-10-06 12:01:06.430932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'e2839191dbbe'
down_revision: Union[str, Sequence[str], None] = '69068a354c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(op.f('idx_landslides_polygon_geom'), table_name='landslides', postgresql_using='gist', column_name='polygon_geom')
    op.drop_geospatial_column('landslides', 'polygon_geom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('landslides', sa.Column('polygon_geom', Geometry(geometry_type='POLYGON', srid=32632, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    op.create_geospatial_index(op.f('idx_landslides_polygon_geom'), 'landslides', ['polygon_geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
