"""remove nullable property of the date column

Revision ID: fe8c60478967
Revises: 0b6d7ef458ee
Create Date: 2025-09-25 18:23:25.439402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8c60478967'
down_revision: Union[str, Sequence[str], None] = '0b6d7ef458ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landslides', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landslides', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
