"""db table structure

Revision ID: c1d5b518cd0a
Revises: 
Create Date: 2025-09-19 17:04:27.769054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c1d5b518cd0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable PostGIS extension
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table('landslides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=32632, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('polygon_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=32632, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_landslides_geom', 'landslides', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_landslides_polygon_geom', 'landslides', ['polygon_geom'], unique=False, postgresql_using='gist')
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('downloaded', sa.Date(), nullable=False),
    sa.Column('modified', sa.Date(), nullable=True),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_index('idx_landslides_polygon_geom', table_name='landslides', postgresql_using='gist')
    op.drop_index('idx_landslides_geom', table_name='landslides', postgresql_using='gist')
    op.drop_table('landslides')
    op.execute("DROP EXTENSION postgis")
    # ### end Alembic commands ###
