"""add foreign key

Revision ID: d786f1744f46
Revises: e67c4c82e1b8
Create Date: 2025-09-22 10:31:22.683366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd786f1744f46'
down_revision: Union[str, Sequence[str], None] = 'e67c4c82e1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslides', sa.Column('source_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'landslides', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landslides', type_='foreignkey')
    op.drop_column('landslides', 'source_id')
    # ### end Alembic commands ###
