"""db table structure

Revision ID: e67c4c82e1b8
Revises: 
Create Date: 2025-09-22 09:07:40.041258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'e67c4c82e1b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION postgis")

    op.create_geospatial_table('landslides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=32632, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('polygon_geom', Geometry(geometry_type='POLYGON', srid=32632, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_landslides_geom', 'landslides', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_landslides_polygon_geom', 'landslides', ['polygon_geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('downloaded', sa.Date(), nullable=False),
    sa.Column('modified', sa.Date(), nullable=True),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_geospatial_index('idx_landslides_polygon_geom', table_name='landslides', postgresql_using='gist', column_name='polygon_geom')
    op.drop_geospatial_index('idx_landslides_geom', table_name='landslides', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('landslides')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION postgis")